/** @type {Record<string, string[]>} */
export default {
  Dog: ["bark", "leash", "puppy", "fetch"],
  Cat: ["meow", "litter", "purr", "whiskers"],
  Puppy: ["cute", "train", "chew", "small"],
  Kitten: ["yarn", "cute", "tiny", "meow"],
  Fish: ["tank", "gills", "swim", "bubbles"],
  Goldfish: ["bowl", "orange", "pet", "swim"],
  Bird: ["feathers", "nest", "fly", "chirp"],
  Parrot: ["talk", "tropical", "colorful", "perch"],
  Hamster: ["wheel", "cage", "cheeks", "small"],
  "Guinea Pig": ["squeak", "cage", "furry", "pet"],
  Rabbit: ["hop", "carrot", "ears", "burrow"],
  Turtle: ["shell", "slow", "pond", "reptile"],
  Snake: ["hiss", "slither", "scales", "reptile"],
  Lizard: ["reptile", "scales", "sun", "tail"],
  Frog: ["ribbit", "pond", "leap", "tadpole"],
  Horse: ["gallop", "stable", "mane", "ride"],
  Pony: ["small", "ride", "mane", "stable"],
  Cow: ["moo", "milk", "farm", "pasture"],
  Pig: ["oink", "mud", "farm", "pink"],
  Sheep: ["wool", "baa", "farm", "flock"],
  Goat: ["bleat", "farm", "horns", "climb"],
  Chicken: ["cluck", "eggs", "farm", "coop"],
  Rooster: ["crow", "dawn", "farm", "comb"],
  Duck: ["quack", "pond", "waddle", "feathers"],
  Goose: ["honk", "migrate", "pond", "flock"],
  Turkey: ["gobble", "Thanksgiving", "farm", "feathers"],
  Mouse: ["squeak", "cheese", "small", "trap"],
  Rat: ["tail", "sewer", "rodent", "cheese"],
  Squirrel: ["acorn", "tree", "nuts", "bushy tail"],
  Chipmunk: ["cheeks", "nuts", "small", "stripe"],
  Raccoon: ["trash", "mask", "night", "paws"],
  Skunk: ["stink", "stripe", "spray", "night"],
  Deer: ["antlers", "forest", "graceful", "buck"],
  Moose: ["antlers", "huge", "forest", "Canada"],
  Bear: ["hibernate", "honey", "cave", "growl"],
  Panda: ["bamboo", "China", "black and white", "cute"],
  Lion: ["roar", "mane", "pride", "savanna"],
  Tiger: ["stripes", "jungle", "roar", "orange"],
  Leopard: ["spots", "climb", "stealth", "big cat"],
  Cheetah: ["fast", "spots", "sprint", "Africa"],
  Elephant: ["trunk", "big", "herd", "tusks"],
  Giraffe: ["tall", "neck", "spots", "Africa"],
  Zebra: ["stripes", "herd", "Africa", "hooves"],
  Hippo: ["river", "huge", "yawn", "Africa"],
  Rhino: ["horn", "charge", "thick skin", "Africa"],
  Monkey: ["banana", "swing", "jungle", "tree"],
  Gorilla: ["strong", "jungle", "chest", "ape"],
  Kangaroo: ["pouch", "hop", "Australia", "joey"],
  Koala: ["eucalyptus", "Australia", "cute", "tree"],
  Fox: ["sly", "den", "bushy tail", "hunt"],
  Wolf: ["howl", "pack", "forest", "wild"],
  Coyote: ["howl", "desert", "wild", "pack"],
  Bat: ["cave", "night", "wings", "echolocation"],
  Owl: ["hoot", "night", "wise", "wings"],
  Eagle: ["soar", "nest", "talons", "America"],
  Hawk: ["soar", "talons", "hunt", "sky"],
  Pigeon: ["city", "coo", "park", "flock"],
  Seagull: ["beach", "fries", "coast", "screech"],
  Penguin: ["Antarctica", "waddle", "ice", "tuxedo"],
  Flamingo: ["pink", "one leg", "tropical", "flock"],
  Peacock: ["feathers", "display", "colorful", "tail"],
  Butterfly: ["wings", "caterpillar", "flower", "metamorphosis"],
  Bee: ["hive", "honey", "buzz", "sting"],
  Ant: ["colony", "tiny", "hill", "march"],
  Spider: ["web", "eight legs", "crawl", "arachnid"],
  Ladybug: ["spots", "red", "garden", "lucky"],
  Worm: ["dirt", "garden", "bait", "wiggle"],
  Snail: ["shell", "slow", "slime", "garden"],
  Shark: ["fin", "ocean", "teeth", "Jaws"],
  Whale: ["ocean", "huge", "spout", "mammal"],
  Dolphin: ["ocean", "smart", "pod", "jump"],
  Seal: ["flippers", "ocean", "bark", "ice"],
  Octopus: ["tentacles", "ocean", "ink", "eight"],
  Jellyfish: ["sting", "ocean", "transparent", "float"],
  Starfish: ["five arms", "ocean", "tide pool", "reef"],
  Crab: ["claws", "beach", "sideways", "shell"],
  Lobster: ["claws", "red", "seafood", "ocean"],
  Shrimp: ["small", "seafood", "peel", "ocean"],
  Clam: ["shell", "beach", "pearl", "ocean"],
  Crocodile: ["swamp", "teeth", "reptile", "snap"],
  Alligator: ["swamp", "teeth", "Florida", "reptile"],
  Camel: ["hump", "desert", "sand", "caravan"],
  Donkey: ["hee-haw", "farm", "stubborn", "pack"],
  Llama: ["spit", "Andes", "wool", "pack"],
  Buffalo: ["herd", "plains", "horns", "strong"],
  Bison: ["plains", "herd", "shaggy", "national park"],
  Reindeer: ["Santa", "antlers", "snow", "sleigh"],
  "Polar Bear": ["Arctic", "ice", "white", "hunt"],
  Sloth: ["slow", "tree", "hang", "jungle"],
  Otter: ["river", "playful", "float", "shell"],
  Beaver: ["dam", "teeth", "river", "lodge"],
  Hedgehog: ["spines", "curl", "small", "garden"],
  Chihuahua: ["tiny", "bark", "Mexico", "purse"],
  Labrador: ["fetch", "friendly", "retriever", "dog"],
  Poodle: ["curly", "fancy", "groom", "France"],
  Bulldog: ["wrinkles", "sturdy", "snort", "face"],
  Husky: ["sled", "blue eyes", "snow", "howl"],
};
