/** @type {Record<string, string[]>} */
export default {
  "Pizza": ["indulgent"],
  "Burger": ["greasy"],
  "Hot Dog": ["ballpark"],
  "Tacos": ["handheld"],
  "Burrito": ["portable"],
  "Nachos": ["shareable"],
  "French Fries": ["dunkable"],
  "Chicken Nuggets": ["cafeteria"],
  "Fried Chicken": ["picnic"],
  "Grilled Cheese": ["nostalgic"],
  "Mac and Cheese": ["nostalgic"],
  "Spaghetti": ["messy"],
  "Pasta": ["weeknight"],
  "Lasagna": ["potluck"],
  "Meatballs": ["hearty"],
  "Soup": ["therapeutic"],
  "Salad": ["virtuous"],
  "Sandwich": ["portable"],
  "PB&J": ["elementary"],
  "Bacon": ["polarizing"],
  "Eggs": ["brunchy"],
  "Pancakes": ["brunchy"],
  "Waffles": ["indulgent"],
  "Cereal": ["cartoonish"],
  "Toast": ["morning"],
  "Bagel": ["urban"],
  "Muffin": ["brunchy"],
  "Donuts": ["indulgent"],
  "Cookies": ["dunkable"],
  "Brownies": ["potluck"],
  "Cake": ["ritualistic"],
  "Cupcake": ["cutesy"],
  "Ice Cream": ["nostalgic"],
  "Popsicle": ["summery"],
  "Candy": ["nostalgic"],
  "Chocolate": ["craving"],
  "Popcorn": ["cinematic"],
  "Chips": ["greasy"],
  "Pretzels": ["stadium"],
  "Apple": ["lunchbox"],
  "Banana": ["portable"],
  "Orange": ["segmented"],
  "Grapes": ["snackable"],
  "Strawberries": ["romantic"],
  "Watermelon": ["picnic"],
  "Carrots": ["virtuous"],
  "Broccoli": ["polarizing"],
  "Corn": ["summery"],
  "Mashed Potatoes": ["comfort"],
  "Rice": ["staple"],
  "Beans": ["budget"],
  "Cheese": ["indulgent"],
  "Butter": ["rich"],
  "Ketchup": ["controversial"],
  "Mustard": ["regional"],
  "Mayo": ["polarizing"],
  "Pickles": ["divisive"],
  "Peanut Butter": ["nostalgic"],
  "Jelly": ["nostalgic"],
  "Honey": ["golden"],
  "Milk": ["staple"],
  "Chocolate Milk": ["nostalgic"],
  "Juice": ["morning"],
  "Apple Juice": ["lunchbox"],
  "Orange Juice": ["brunchy"],
  "Lemonade": ["summery"],
  "Water": ["plain"],
  "Soda": ["bubbly"],
  "Iced Tea": ["refreshing"],
  "Hot Chocolate": ["cozy"],
  "Coffee": ["ritualistic"],
  "Tea": ["ritualistic"],
  "Smoothie": ["trendy"],
  "Milkshake": ["indulgent"],
  "Sushi": ["trendy"],
  "Ramen": ["collegiate"],
  "Stir Fry": ["weeknight"],
  "Fish Sticks": ["nostalgic"],
  "Tater Tots": ["cafeteria"],
  "Quesadilla": ["handheld"],
  "Guacamole": ["trendy"],
  "Salsa": ["festive"],
  "Omelet": ["upscale"],
  "Steak": ["celebratory"],
  "Shrimp": ["coastal"],
  "Crab Legs": ["messy"],
  "Lobster": ["celebratory"],
  "Pizza Rolls": ["microwavable"],
  "Instant Noodles": ["collegiate"],
  "Granola Bar": ["outdoorsy"],
  "Yogurt": ["virtuous"],
  "String Cheese": ["playful"],
  "Goldfish Crackers": ["nostalgic"],
  "Gummy Bears": ["chewy"],
  "Root Beer": ["retro"],
  "Ginger Ale": ["soothing"],
};
