/** @type {Record<string, string[]>} */
export default {
  "Teacher": ["authoritative"],
  "Student": ["mandatory"],
  "Principal": ["authoritative"],
  "Librarian": ["quiet"],
  "Coach": ["motivating"],
  "Doctor": ["credentialed"],
  "Nurse": ["credentialed"],
  "Dentist": ["clinical"],
  "Vet": ["clinical"],
  "Firefighter": ["hazardous"],
  "Police Officer": ["uniformed"],
  "Detective": ["investigative"],
  "Soldier": ["uniformed"],
  "Pilot": ["credentialed"],
  "Flight Attendant": ["uniformed"],
  "Bus Driver": ["routine"],
  "Taxi Driver": ["freelance"],
  "Uber Driver": ["freelance"],
  "Truck Driver": ["solitary"],
  "Mail Carrier": ["routine"],
  "Delivery Driver": ["freelance"],
  "Chef": ["creative"],
  "Cook": ["repetitive"],
  "Waiter": ["tipped"],
  "Waitress": ["tipped"],
  "Barista": ["repetitive"],
  "Bartender": ["nocturnal"],
  "Cashier": ["repetitive"],
  "Store Clerk": ["repetitive"],
  "Manager": ["supervisory"],
  "Boss": ["authoritative"],
  "CEO": ["executive"],
  "Farmer": ["seasonal"],
  "Gardener": ["manual"],
  "Landscaper": ["manual"],
  "Construction Worker": ["hazardous"],
  "Builder": ["manual"],
  "Carpenter": ["manual"],
  "Plumber": ["manual"],
  "Electrician": ["licensed"],
  "Mechanic": ["manual"],
  "Car Wash": ["repetitive"],
  "Hair Stylist": ["creative"],
  "Barber": ["social"],
  "Makeup Artist": ["creative"],
  "Nail Tech": ["meticulous"],
  "Fashion Designer": ["creative"],
  "Tailor": ["meticulous"],
  "Model": ["glamorized"],
  "Actor": ["glamorized"],
  "Actress": ["glamorized"],
  "Singer": ["performative"],
  "Musician": ["creative"],
  "DJ": ["nocturnal"],
  "Dancer": ["performative"],
  "Artist": ["creative"],
  "Painter": ["creative"],
  "Photographer": ["creative"],
  "YouTuber": ["entrepreneurial"],
  "Streamer": ["entrepreneurial"],
  "Influencer": ["glamorized"],
  "Writer": ["solitary"],
  "Author": ["solitary"],
  "Journalist": ["investigative"],
  "News Reporter": ["investigative"],
  "News Anchor": ["televised"],
  "Weather Person": ["televised"],
  "Scientist": ["credentialed"],
  "Astronaut": ["credentialed"],
  "Engineer": ["technical"],
  "Computer Guy": ["technical"],
  "Programmer": ["technical"],
  "Gamer": ["sedentary"],
  "Lawyer": ["adversarial"],
  "Judge": ["authoritative"],
  "Banker": ["corporate"],
  "Accountant": ["meticulous"],
  "Real Estate Agent": ["commissioned"],
  "Salesperson": ["commissioned"],
  "Realtor": ["commissioned"],
  "Babysitter": ["freelance"],
  "Nanny": ["domestic"],
  "Daycare Worker": ["repetitive"],
  "Lifeguard": ["seasonal"],
  "Park Ranger": ["seasonal"],
  "Zookeeper": ["specialized"],
  "Dog Walker": ["freelance"],
  "Pet Sitter": ["freelance"],
  "Veterinarian": ["clinical"],
  "Therapist": ["confidential"],
  "Counselor": ["confidential"],
  "Social Worker": ["underpaid"],
  "Paramedic": ["hazardous"],
  "EMT": ["hazardous"],
  "Surgeon": ["credentialed"],
  "Pharmacist": ["licensed"],
  "Lab Worker": ["clinical"],
  "Archaeologist": ["specialized"],
  "Tour Guide": ["seasonal"],
  "Hotel Worker": ["hospitality"],
  "Housekeeper": ["invisible"],
  "Janitor": ["invisible"],
  "Security Guard": ["nocturnal"],
  "Bouncer": ["intimidating"],
  "Magician": ["performative"],
  "Clown": ["performative"],
  "Party Planner": ["creative"],
  "Wedding Planner": ["stressful"],
  "Florist": ["creative"],
  "Baker": ["creative"],
  "Butcher": ["manual"],
  "Ice Cream Man": ["nostalgic"],
  "Food Truck Owner": ["entrepreneurial"],
  "Entrepreneur": ["risky"],
  "Business Owner": ["entrepreneurial"],
  "Intern": ["underpaid"],
  "Volunteer": ["unpaid"],
  "School Bus Driver": ["routine"],
  "Crossing Guard": ["seasonal"],
  "Custodian": ["invisible"],
};
