/** @type {Record<string, string[]>} */
export default {
  "Movie": ["cinematic", "theatrical"],
  "TV Show": ["serial", "bingeable"],
  "Cartoon": ["stylized", "whimsical"],
  "Anime": ["kinetic", "expressive"],
  "Comedy": ["irreverent", "farcical"],
  "Funny Movie": ["lighthearted", "absurd"],
  "Scary Movie": ["unsettling", "visceral"],
  "Horror": ["macabre", "dreadful"],
  "Action Movie": ["kinetic", "explosive"],
  "Adventure": ["sprawling", "perilous"],
  "Romance": ["wistful", "melodramatic"],
  "Love Story": ["bittersweet", "yearning"],
  "Superhero": ["mythic", "caped"],
  "Disney": ["wholesome", "formulaic"],
  "Pixar": ["heartfelt", "anthropomorphic"],
  "Netflix": ["bingeable", "algorithmic"],
  "YouTube": ["grassroots", "evergreen"],
  "TikTok": ["snappy", "viral"],
  "Reality TV": ["unscripted", "voyeuristic"],
  "Game Show": ["competitive", "ceremonial"],
  "Talk Show": ["conversational", "topical"],
  "News": ["topical", "urgent"],
  "Sports on TV": ["broadcast", "perennial"],
  "Cooking Show": ["sensory", "instructional"],
  "Talent Show": ["aspirational", "competitive"],
  "Sitcom": ["formulaic", "domestic"],
  "Drama": ["intense", "heightened"],
  "Mystery": ["labyrinthine", "suspenseful"],
  "Crime Show": ["procedural", "murky"],
  "Zombie": ["apocalyptic", "relentless"],
  "Vampire": ["nocturnal", "gothic"],
  "Alien": ["otherworldly", "uncanny"],
  "Robot": ["mechanized", "synthetic"],
  "Dragon": ["mythical", "imposing"],
  "Wizard": ["arcane", "mystical"],
  "Princess": ["regal", "archetypal"],
  "Prince": ["gallant", "regal"],
  "King": ["sovereign", "imposing"],
  "Queen": ["regal", "commanding"],
  "Pirate": ["swashbuckling", "lawless"],
  "Ninja": ["stealthy", "lethal"],
  "Spy": ["clandestine", "surveilled"],
  "Detective": ["deductive", "observant"],
  "Police Show": ["procedural", "gritty"],
  "Hospital Show": ["melodramatic", "institutional"],
  "School Show": ["adolescent", "nostalgic"],
  "Family Movie": ["wholesome", "multigenerational"],
  "Kids Movie": ["whimsical", "accessible"],
  "Christmas Movie": ["seasonal", "saccharine"],
  "Halloween Special": ["spooky", "seasonal"],
  "Music Video": ["synesthetic", "glossy"],
  "Concert": ["electrifying", "communal"],
  "Stand-Up Comedy": ["irreverent", "intimate"],
  "Documentary": ["journalistic", "sobering"],
  "Nature Show": ["panoramic", "verdant"],
  "Animal Show": ["educational", "observational"],
  "True Crime": ["sensational", "forensic"],
  "Soap Opera": ["melodramatic", "convoluted"],
  "Western": ["dusty", "laconic"],
  "Space Movie": ["cosmic", "expansive"],
  "Time Travel": ["paradoxical", "recursive"],
  "Sequel": ["franchised", "repetitive"],
  "Remake": ["rehashed", "polarizing"],
  "Trailer": ["tantalizing", "abbreviated"],
  "Credits": ["ceremonious", "exhaustive"],
  "Popcorn at Movies": ["buttery", "communal"],
  "Drive-In": ["retro", "nostalgic"],
  "3D Movie": ["immersive", "gimmicky"],
  "Subtitles": ["translated", "literate"],
  "Binge Watching": ["compulsive", "marathon"],
  "Season Finale": ["climactic", "anticipated"],
  "Plot Twist": ["subversive", "startling"],
  "Happy Ending": ["uplifting", "cathartic"],
  "Sad Ending": ["tragic", "devastating"],
  "Jump Scare": ["startling", "abrupt"],
  "Fight Scene": ["choreographed", "brutal"],
  "Chase Scene": ["breathless", "kinetic"],
  "Love Triangle": ["messy", "jealous"],
  "Best Friend": ["steadfast", "platonic"],
  "Villain": ["menacing", "charismatic"],
  "Hero": ["triumphant", "archetypal"],
  "Sidekick": ["comedic", "secondary"],
  "Oscars": ["prestigious", "politicized"],
  "Red Carpet": ["glamorous", "ceremonial"],
  "Movie Star": ["luminous", "bankable"],
  "Actor": ["charismatic", "transformative"],
  "Actress": ["charismatic", "transformative"],
  "Director": ["visionary", "auteurist"],
  "Camera": ["voyeuristic", "immersive"],
  "Microphone": ["resonant", "intimate"],
  "Theme Song": ["earworm", "iconic"],
  "Catchphrase": ["quotable", "memeable"],
  "Spoiler": ["ruinous", "indiscreet"],
  "Fan": ["obsessive", "devoted"],
  "Marvel": ["expansive", "interconnected"],
  "Star Wars": ["operatic", "mythic"],
  "Harry Potter": ["enchanting", "collegiate"],
};
