/** @type {Record<string, string[]>} */
export default {
  "Sun": ["radiant"],
  "Moon": ["romanticized"],
  "Stars": ["romanticized"],
  "Sky": ["expansive"],
  "Cloud": ["ephemeral"],
  "Rain": ["unpredictable"],
  "Snow": ["seasonal"],
  "Hail": ["violent"],
  "Wind": ["invisible"],
  "Storm": ["dramatic"],
  "Thunder": ["ominous"],
  "Lightning": ["sudden"],
  "Rainbow": ["ephemeral"],
  "Fog": ["mysterious"],
  "Mist": ["mysterious"],
  "Hot": ["uncomfortable"],
  "Cold": ["harsh"],
  "Warm": ["pleasant"],
  "Sunny Day": ["postcard"],
  "Rainy Day": ["gloomy"],
  "Snow Day": ["nostalgic"],
  "Sunrise": ["romanticized"],
  "Sunset": ["romanticized"],
  "Night": ["mysterious"],
  "Day": ["routine"],
  "Spring": ["renewing"],
  "Summer": ["touristy"],
  "Fall": ["nostalgic"],
  "Winter": ["harsh"],
  "Tree": ["ancient"],
  "Bush": ["overgrown"],
  "Grass": ["mundane"],
  "Flower": ["decorative"],
  "Rose": ["romanticized"],
  "Tulip": ["touristy"],
  "Daisy": ["mundane"],
  "Sunflower": ["photogenic"],
  "Dandelion": ["childhood"],
  "Leaf": ["ephemeral"],
  "Branch": ["fragile"],
  "Stick": ["mundane"],
  "Rock": ["ancient"],
  "Stone": ["ancient"],
  "Pebble": ["mundane"],
  "Sand": ["shifting"],
  "Dirt": ["mundane"],
  "Mud": ["messy"],
  "Puddle": ["ephemeral"],
  "Hill": ["rolling"],
  "Mountain": ["majestic"],
  "Valley": ["serene"],
  "Cliff": ["ominous"],
  "Cave": ["mysterious"],
  "Forest": ["dense"],
  "Woods": ["dense"],
  "Jungle": ["humid"],
  "Field": ["open"],
  "Meadow": ["serene"],
  "Garden": ["cultivated"],
  "Farm": ["cultivated"],
  "Lake": ["serene"],
  "Pond": ["serene"],
  "River": ["flowing"],
  "Stream": ["flowing"],
  "Waterfall": ["dramatic"],
  "Ocean": ["vast"],
  "Sea": ["vast"],
  "Beach": ["touristy"],
  "Wave": ["rhythmic"],
  "Island": ["isolated"],
  "Desert": ["arid"],
  "Cactus": ["arid"],
  "Palm Tree": ["tropical"],
  "Pine Tree": ["eternal"],
  "Oak Tree": ["ancient"],
  "Apple Tree": ["cultivated"],
  "Cherry Blossom": ["touristy"],
  "Mushroom": ["mysterious"],
  "Acorn": ["seasonal"],
  "Pinecone": ["seasonal"],
  "Nest": ["hidden"],
  "Bird's Nest": ["hidden"],
  "Honey": ["sweet"],
  "Beehive": ["buzzing"],
  "Butterfly": ["delicate"],
  "Caterpillar": ["transforming"],
  "Ant Hill": ["organized"],
  "Spider Web": ["delicate"],
  "Shell": ["fragile"],
  "Seashell": ["collectible"],
  "Coral": ["colorful"],
  "Seaweed": ["slippery"],
  "Tide Pool": ["ephemeral"],
  "Sandcastle": ["ephemeral"],
  "Snowman": ["nostalgic"],
  "Icicle": ["sharp"],
  "Frost": ["delicate"],
  "Ice": ["slippery"],
  "Fire": ["destructive"],
  "Campfire": ["nostalgic"],
  "Smoke": ["ominous"],
  "Volcano": ["unpredictable"],
  "Earthquake": ["seismic"],
  "Flood": ["destructive"],
  "Tornado": ["unpredictable"],
  "Hurricane": ["destructive"],
  "Blizzard": ["harsh"],
  "Avalanche": ["sudden"],
  "Wildfire": ["destructive"],
  "Full Moon": ["romanticized"],
  "Shooting Star": ["ephemeral"],
  "Planet": ["distant"],
  "Earth": ["fragile"],
  "Mars": ["distant"],
  "Outer Space": ["otherworldly"],
  "Rocket": ["loud"],
  "Astronaut": ["prestigious"],
  "UFO": ["controversial"],
  "Camping": ["rustic"],
  "Hiking": ["exhausting"],
  "Fishing": ["patient"],
  "Picnic": ["leisurely"],
  "National Park": ["protected"],
  "Pet": ["domestic"],
  "Bug": ["annoying"],
  "Worm": ["slimy"],
  "Fresh Air": ["unstable"],
};
