/** @type {Record<string, string[]>} */
export default {
  Sun: ["bright", "day", "warm", "sky"],
  Moon: ["night", "phases", "glow", "tide"],
  Stars: ["night", "twinkle", "sky", "constellation"],
  Sky: ["clouds", "blue", "above", "fly"],
  Cloud: ["rain", "fluffy", "sky", "gray"],
  Rain: ["wet", "umbrella", "puddles", "storm"],
  Snow: ["cold", "flake", "winter", "white"],
  Hail: ["ice", "storm", "pellets", "damage"],
  Wind: ["blow", "breeze", "gust", "kite"],
  Storm: ["thunder", "dark", "rain", "wind"],
  Thunder: ["loud", "boom", "lightning", "storm"],
  Lightning: ["flash", "bolt", "storm", "zigzag"],
  Rainbow: ["colors", "rain", "arc", "pot of gold"],
  Fog: ["mist", "thick", "drive slow", "gray"],
  Mist: ["haze", "morning", "damp", "soft"],
  Hot: ["summer", "sweat", "sun", "heat"],
  Cold: ["winter", "shiver", "ice", "coat"],
  Warm: ["cozy", "sun", "spring", "pleasant"],
  "Sunny Day": ["bright", "park", "shade", "summer"],
  "Rainy Day": ["umbrella", "puddles", "inside", "gray"],
  "Snow Day": ["no school", "sled", "white", "cold"],
  Sunrise: ["morning", "horizon", "early", "gold"],
  Sunset: ["evening", "horizon", "orange", "pretty"],
  Night: ["dark", "stars", "moon", "sleep"],
  Day: ["sun", "bright", "awake", "sky"],
  Spring: ["flowers", "bloom", "rain", "warm"],
  Summer: ["hot", "beach", "vacation", "sun"],
  Fall: ["leaves", "pumpkin", "cool", "harvest"],
  Winter: ["snow", "cold", "coat", "holidays"],
  Tree: ["leaves", "trunk", "shade", "climb"],
  Bush: ["shrubs", "garden", "green", "trim"],
  Grass: ["lawn", "mow", "green", "yard"],
  Flower: ["petals", "bloom", "garden", "smell"],
  Rose: ["thorns", "red", "romance", "garden"],
  Tulip: ["spring", "bulb", "colorful", "garden"],
  Daisy: ["white", "petals", "field", "simple"],
  Sunflower: ["tall", "yellow", "seeds", "face"],
  Dandelion: ["wish", "blow", "yellow", "weed"],
  Leaf: ["fall", "green", "tree", "crunch"],
  Branch: ["tree", "bird", "snap", "wood"],
  Stick: ["dog", "fetch", "wood", "poke"],
  Rock: ["hard", "throw", "skip", "stone"],
  Stone: ["hard", "pebble", "heavy", "gray"],
  Pebble: ["small", "beach", "skip", "smooth"],
  Sand: ["beach", "castle", "hot", "grain"],
  Dirt: ["mud", "garden", "brown", "dig"],
  Mud: ["puddle", "messy", "boots", "brown"],
  Puddle: ["rain", "splash", "jump", "reflect"],
  Hill: ["climb", "roll down", "slope", "grass"],
  Mountain: ["peak", "hike", "tall", "snow"],
  Valley: ["between", "low", "river", "green"],
  Cliff: ["edge", "drop", "steep", "view"],
  Cave: ["dark", "explore", "bat", "underground"],
  Forest: ["trees", "woods", "trail", "shade"],
  Woods: ["trees", "trail", "quiet", "hike"],
  Jungle: ["tropical", "dense", "humid", "vines"],
  Field: ["open", "grass", "farm", "wide"],
  Meadow: ["flowers", "grass", "peaceful", "open"],
  Garden: ["plants", "grow", "water", "yard"],
  Farm: ["barn", "crops", "tractor", "animals"],
  Lake: ["dock", "fish", "calm", "swim"],
  Pond: ["frogs", "ducks", "small", "lily pad"],
  River: ["flow", "current", "bridge", "fish"],
  Stream: ["babble", "brook", "small", "rocks"],
  Waterfall: ["mist", "roar", "cliff", "spray"],
  Ocean: ["waves", "salt", "vast", "deep"],
  Sea: ["salt", "waves", "sail", "deep"],
  Beach: ["sand", "waves", "shells", "towel"],
  Wave: ["crash", "surf", "ocean", "foam"],
  Island: ["tropical", "surrounded", "palm", "boat"],
  Desert: ["sand", "hot", "cactus", "dry"],
  Cactus: ["spines", "desert", "dry", "succulent"],
  "Palm Tree": ["tropical", "coconut", "beach", "fronds"],
  "Pine Tree": ["needles", "cone", "Christmas", "evergreen"],
  "Oak Tree": ["acorn", "strong", "shade", "leaves"],
  "Apple Tree": ["orchard", "fruit", "bloom", "pie"],
  "Cherry Blossom": ["pink", "spring", "Japan", "petals"],
  Mushroom: ["fungi", "forest", "toadstool", "spore"],
  Acorn: ["oak", "squirrel", "nut", "fall"],
  Pinecone: ["pine", "craft", "fall", "scales"],
  Nest: ["eggs", "birds", "twigs", "tree"],
  "Bird's Nest": ["eggs", "twigs", "tree", "chirp"],
  Honey: ["bees", "sweet", "hive", "bear"],
  Beehive: ["buzz", "honey", "hexagon", "sting"],
  Butterfly: ["wings", "caterpillar", "flower", "flutter"],
  Caterpillar: ["cocoon", "leaf", "fuzzy", "butterfly"],
  "Ant Hill": ["colony", "tiny", "dirt", "march"],
  "Spider Web": ["silk", "dew", "corner", "trap"],
  Shell: ["beach", "ocean", "collect", "spiral"],
  Seashell: ["beach", "ocean", "listen", "collect"],
  Coral: ["reef", "ocean", "colorful", "fish"],
  Seaweed: ["ocean", "sushi wrap", "tide", "green"],
  "Tide Pool": ["crab", "starfish", "rocks", "shore"],
  Sandcastle: ["beach", "bucket", "moat", "wave"],
  Snowman: ["carrot nose", "winter", "three balls", "melt"],
  Icicle: ["hang", "winter", "drip", "sharp"],
  Frost: ["morning", "window", "cold", "crystals"],
  Ice: ["cold", "skate", "cube", "freeze"],
  Fire: ["flame", "hot", "camp", "burn"],
  Campfire: ["marshmallow", "smoke", "stories", "woods"],
  Smoke: ["fire", "gray", "chimney", "rise"],
  Volcano: ["lava", "erupt", "ash", "magma"],
  Earthquake: ["shake", "rumble", "fault", "tremor"],
  Flood: ["water", "rise", "rain", "damage"],
  Tornado: ["funnel", "spin", "siren", "debris"],
  Hurricane: ["eye", "wind", "coast", "storm"],
  Blizzard: ["snow", "whiteout", "cold", "wind"],
  Avalanche: ["snow", "mountain", "bury", "slide"],
  Wildfire: ["smoke", "forest", "spread", "evacuate"],
  "Full Moon": ["howl", "bright", "night", "werewolf"],
  "Shooting Star": ["wish", "streak", "night", "meteor"],
  Planet: ["orbit", "space", "round", "solar"],
  Earth: ["home", "blue", "orbit", "life"],
  Mars: ["red", "rover", "planet", "space"],
  "Outer Space": ["stars", "void", "astronaut", "rocket"],
  Rocket: ["launch", "blast off", "NASA", "space"],
  Astronaut: ["helmet", "float", "space", "suit"],
  UFO: ["alien", "flying saucer", "mystery", "lights"],
  Camping: ["tent", "fire", "woods", "s'mores"],
  Hiking: ["trail", "boots", "backpack", "mountain"],
  Fishing: ["rod", "bait", "lake", "reel"],
  Picnic: ["blanket", "basket", "park", "ants"],
  "National Park": ["ranger", "trail", "nature", "preserve"],
  Pet: ["home", "feed", "love", "companion"],
  Bug: ["crawl", "small", "garden", "insect"],
  Worm: ["dirt", "bait", "wiggle", "rain"],
  "Fresh Air": ["breathe", "outside", "park", "breeze"],
};
