/** @type {Record<string, string[]>} */
export default {
  "Phone": ["ubiquitous"],
  "iPhone": ["branded"],
  "Laptop": ["portable"],
  "Computer": ["deskbound"],
  "Tablet": ["portable"],
  "TV": ["household"],
  "Remote": ["losable"],
  "Headphones": ["wearable"],
  "Earbuds": ["wearable"],
  "Speaker": ["noisy"],
  "Charger": ["essential"],
  "Cable": ["tangled"],
  "Camera": ["nostalgic"],
  "Selfie Stick": ["conspicuous"],
  "Watch": ["wearable"],
  "Clock": ["ubiquitous"],
  "Alarm Clock": ["annoying"],
  "Calendar": ["organized"],
  "Backpack": ["portable"],
  "Purse": ["personal"],
  "Wallet": ["losable"],
  "Keys": ["essential"],
  "Sunglasses": ["seasonal"],
  "Glasses": ["essential"],
  "Hat": ["wearable"],
  "Cap": ["casual"],
  "Jacket": ["seasonal"],
  "Coat": ["seasonal"],
  "Shoes": ["essential"],
  "Sneakers": ["casual"],
  "Socks": ["disposable"],
  "Belt": ["functional"],
  "Umbrella": ["seasonal"],
  "Raincoat": ["seasonal"],
  "Towel": ["reusable"],
  "Soap": ["disposable"],
  "Shampoo": ["disposable"],
  "Toothbrush": ["replaceable"],
  "Toothpaste": ["disposable"],
  "Hairbrush": ["personal"],
  "Comb": ["personal"],
  "Mirror": ["reflective"],
  "Tissue": ["disposable"],
  "Toilet Paper": ["essential"],
  "Band-Aid": ["disposable"],
  "Medicine": ["regulated"],
  "Pill": ["regulated"],
  "Water Bottle": ["reusable"],
  "Cup": ["disposable"],
  "Mug": ["personal"],
  "Plate": ["disposable"],
  "Bowl": ["disposable"],
  "Fork": ["disposable"],
  "Spoon": ["disposable"],
  "Knife": ["sharp"],
  "Napkin": ["disposable"],
  "Straw": ["controversial"],
  "Lunch Box": ["nostalgic"],
  "Thermos": ["portable"],
  "Cooler": ["seasonal"],
  "Fridge": ["essential"],
  "Microwave": ["convenient"],
  "Oven": ["essential"],
  "Stove": ["essential"],
  "Toaster": ["convenient"],
  "Blender": ["noisy"],
  "Pot": ["essential"],
  "Pan": ["essential"],
  "Spatula": ["functional"],
  "Trash Can": ["essential"],
  "Broom": ["functional"],
  "Mop": ["functional"],
  "Vacuum": ["noisy"],
  "Laundry Basket": ["functional"],
  "Washing Machine": ["essential"],
  "Dryer": ["essential"],
  "Iron": ["functional"],
  "Hanger": ["functional"],
  "Bed": ["essential"],
  "Pillow": ["comfortable"],
  "Blanket": ["comfortable"],
  "Sheets": ["replaceable"],
  "Couch": ["comfortable"],
  "Chair": ["ubiquitous"],
  "Table": ["ubiquitous"],
  "Desk": ["industrial"],
  "Lamp": ["ambient"],
  "Light": ["essential"],
  "Fan": ["seasonal"],
  "AC": ["essential"],
  "Heater": ["seasonal"],
  "Door": ["essential"],
  "Window": ["essential"],
  "Curtain": ["decorative"],
  "Rug": ["decorative"],
  "Carpet": ["decorative"],
  "Picture Frame": ["sentimental"],
  "Poster": ["decorative"],
  "Book": ["nostalgic"],
  "Notebook": ["disposable"],
  "Pen": ["losable"],
  "Pencil": ["disposable"],
  "Eraser": ["disposable"],
  "Marker": ["permanent"],
  "Crayons": ["nostalgic"],
  "Scissors": ["sharp"],
  "Tape": ["adhesive"],
  "Glue": ["adhesive"],
  "Stapler": ["office"],
  "Paper": ["disposable"],
  "Homework": ["dreaded"],
  "Backpack": ["portable"],
  "Pencil Case": ["nostalgic"],
  "Calculator": ["regulated"],
  "Ruler": ["regulated"],
  "Globe": ["educational"],
  "Map": ["outdated"],
  "Flashlight": ["emergency"],
  "Batteries": ["disposable"],
  "Candle": ["ambient"],
  "Lighter": ["regulated"],
  "Matches": ["disposable"],
  "Hammer": ["manual"],
  "Screwdriver": ["manual"],
  "Toolbox": ["manual"],
  "Duct Tape": ["improvised"],
  "Ball": ["playful"],
  "Football": ["outdoor"],
  "Basketball": ["outdoor"],
  "Baseball": ["nostalgic"],
  "Bat": ["sporting"],
  "Glove": ["sporting"],
  "Bike": ["portable"],
  "Helmet": ["protective"],
  "Skateboard": ["rebellious"],
  "Scooter": ["childhood"],
  "Tent": ["seasonal"],
  "Sleeping Bag": ["seasonal"],
  "Board Game": ["nostalgic"],
  "Cards": ["nostalgic"],
  "Dice": ["random"],
  "Puzzle": ["patient"],
  "Teddy Bear": ["sentimental"],
  "Toy": ["nostalgic"],
  "Legos": ["creative"],
  "Doll": ["nostalgic"],
  "Action Figure": ["collectible"],
  "Video Game": ["sedentary"],
  "Controller": ["ergonomic"],
  "Gift": ["ceremonial"],
  "Present": ["ceremonial"],
  "Wrapping Paper": ["disposable"],
  "Balloon": ["festive"],
  "Birthday Cake": ["ceremonial"],
  "Candles": ["ceremonial"],
  "Party Hat": ["festive"],
  "Confetti": ["messy"],
  "Money": ["essential"],
  "Coins": ["losable"],
  "Dollar Bill": ["paper"],
  "Credit Card": ["digital"],
  "Receipt": ["disposable"],
  "Shopping Bag": ["disposable"],
  "Cart": ["wheeled"],
  "Basket": ["woven"],
  "Suitcase": ["travel"],
  "Passport": ["regulated"],
  "Ticket": ["disposable"],
  "Boarding Pass": ["disposable"],
  "License": ["regulated"],
  "ID Card": ["regulated"],
};
