/** @type {Record<string, string[]>} */
export default {
  Home: ["family", "door", "cozy", "where you live"],
  House: ["roof", "yard", "rooms", "family"],
  Apartment: ["building", "rent", "neighbor", "floor"],
  Bedroom: ["bed", "sleep", "pillow", "door"],
  Bathroom: ["shower", "toilet", "mirror", "sink"],
  Kitchen: ["stove", "fridge", "cook", "sink"],
  "Living Room": ["couch", "TV", "family", "relax"],
  Backyard: ["grass", "fence", "grill", "play"],
  Garage: ["car", "tools", "door", "park"],
  Basement: ["stairs", "storage", "dark", "below"],
  School: ["class", "bell", "homework", "teachers"],
  Classroom: ["desk", "board", "teacher", "students"],
  Cafeteria: ["lunch", "tray", "line", "food"],
  Gym: ["basketball", "sweat", "PE", "bleachers"],
  Playground: ["swings", "slide", "recess", "kids"],
  Library: ["books", "quiet", "shelf", "read"],
  Office: ["desk", "computer", "meeting", "work"],
  Store: ["shop", "aisles", "checkout", "buy"],
  "Grocery Store": ["cart", "aisles", "checkout", "food"],
  Mall: ["shops", "food court", "walk", "spend"],
  Restaurant: ["menu", "waiter", "table", "eat out"],
  "Fast Food": ["drive-thru", "quick", "fries", "counter"],
  Cafe: ["coffee", "pastry", "sit", "espresso"],
  Bakery: ["bread", "pastry", "oven", "smell"],
  "Movie Theater": ["popcorn", "screen", "tickets", "dark"],
  Park: ["bench", "trees", "picnic", "walk"],
  Beach: ["sand", "waves", "sun", "towel"],
  Pool: ["swim", "chlorine", "diving board", "summer"],
  Zoo: ["animals", "cages", "exhibits", "family"],
  Museum: ["art", "exhibits", "quiet", "history"],
  Hospital: ["doctor", "nurse", "sick", "emergency"],
  "Doctor's Office": ["checkup", "waiting room", "stethoscope", "appointment"],
  Dentist: ["teeth", "drill", "chair", "floss"],
  Pharmacy: ["medicine", "prescription", "pills", "counter"],
  Bank: ["money", "teller", "ATM", "deposit"],
  "Post Office": ["mail", "stamps", "package", "letters"],
  "Police Station": ["badge", "cops", "report", "squad car"],
  "Fire Station": ["truck", "hose", "firefighters", "alarm"],
  Church: ["pew", "sermon", "steeple", "Sunday"],
  Airport: ["planes", "terminal", "security", "gate"],
  "Train Station": ["tracks", "platform", "commute", "ticket"],
  "Bus Stop": ["bench", "route", "commute", "wait"],
  "Gas Station": ["pump", "fuel", "car", "snacks"],
  "Parking Lot": ["cars", "spaces", "mall", "ticket"],
  Hotel: ["lobby", "room key", "vacation", "check in"],
  Campground: ["tent", "fire", "woods", "sleep"],
  Farm: ["barn", "animals", "crops", "tractor"],
  Barn: ["hay", "animals", "red", "farm"],
  Forest: ["trees", "trail", "woods", "hike"],
  Mountains: ["peak", "hike", "snow", "view"],
  Lake: ["dock", "fish", "boat", "swim"],
  River: ["flow", "bridge", "fish", "current"],
  Ocean: ["waves", "salt", "beach", "vast"],
  Island: ["beach", "palm", "boat", "tropical"],
  Desert: ["sand", "hot", "cactus", "dry"],
  Cave: ["dark", "explore", "stalactite", "underground"],
  Waterfall: ["mist", "cliff", "roar", "hike"],
  Stadium: ["crowd", "cheer", "field", "game"],
  "Soccer Field": ["goal", "grass", "cleats", "match"],
  "Basketball Court": ["hoop", "lines", "dribble", "gym"],
  "Skate Park": ["ramp", "grind", "wheels", "tricks"],
  "Bowling Alley": ["lanes", "pins", "shoes", "strike"],
  Arcade: ["tokens", "games", "prizes", "loud"],
  "Amusement Park": ["rides", "lines", "fun", "tickets"],
  "Roller Coaster": ["scream", "drops", "tracks", "thrill"],
  "Water Park": ["slides", "splash", "summer", "pool"],
  Disneyland: ["Mickey", "rides", "magic", "lines"],
  "Grandma's House": ["cookies", "hugs", "family", "visit"],
  "Friend's House": ["playdate", "hang out", "sleepover", "visit"],
  Daycare: ["kids", "toys", "nap time", "care"],
  College: ["campus", "dorm", "lecture", "degree"],
  Dorm: ["roommate", "campus", "small", "college"],
  "Locker Room": ["gym", "locker", "shoes", "PE"],
  "Nurse's Office": ["band-aid", "sick", "school", "ice pack"],
  "Principal's Office": ["trouble", "school", "serious", "detention"],
  Barbershop: ["haircut", "clippers", "mirror", "chair"],
  "Hair Salon": ["cut", "color", "blow dry", "appointment"],
  Laundromat: ["washers", "dryers", "quarters", "clothes"],
  "Pet Store": ["puppies", "fish tank", "food", "animals"],
  "Toy Store": ["toys", "kids", "aisles", "birthday"],
  Bookstore: ["shelves", "read", "browse", "coffee"],
  "Hardware Store": ["tools", "nails", "DIY", "paint"],
  Costco: ["bulk", "samples", "warehouse", "cart"],
  Walmart: ["aisles", "everyday low", "cart", "big store"],
  Target: ["red cart", "aisles", "bullseye", "shop"],
  "McDonald's": ["fries", "golden arches", "drive-thru", "happy meal"],
  Starbucks: ["coffee", "latte", "green apron", "cup"],
  Subway: ["sandwich", "footlong", "train name", "bread"],
  Downtown: ["city", "buildings", "busy", "shops"],
  Neighborhood: ["block", "houses", "local", "community"],
  Sidewalk: ["walk", "chalk", "curb", "street"],
  Street: ["cars", "crosswalk", "lamps", "drive"],
  Bridge: ["river", "cross", "span", "toll"],
  Tunnel: ["dark", "through", "echo", "under"],
  Highway: ["fast", "lanes", "exit", "road trip"],
};
