/** @type {Record<string, string[]>} */
export default {
  "Home": ["domestic", "habitual"],
  "House": ["residential", "mortgaged"],
  "Apartment": ["rented", "stacked"],
  "Bedroom": ["private", "nocturnal"],
  "Bathroom": ["tiled", "steamy"],
  "Kitchen": ["aromatic", "culinary"],
  "Living Room": ["lounging", "communal"],
  "Backyard": ["fenced", "suburban"],
  "Garage": ["cluttered", "paved"],
  "Basement": ["subterranean", "damp"],
  "School": ["institutional", "scheduled"],
  "Classroom": ["seated", "instructional"],
  "Cafeteria": ["trayed", "institutional"],
  "Gym": ["sweaty", "rebounding"],
  "Playground": ["scraped", "outdoor"],
  "Library": ["hushed", "borrowable"],
  "Office": ["cubicular", "fluorescent"],
  "Store": ["merchandised", "checkout"],
  "Grocery Store": ["perishable", "carted"],
  "Mall": ["fluorescent", "queued"],
  "Restaurant": ["plated", "reservable"],
  "Fast Food": ["expedited", "disposable"],
  "Cafe": ["caffeinated", "lingering"],
  "Bakery": ["yeasty", "morning"],
  "Movie Theater": ["dimmed", "buttered"],
  "Park": ["grassy", "leisurely"],
  "Beach": ["sandy", "sunburnt"],
  "Pool": ["chlorinated", "splashing"],
  "Zoo": ["caged", "exotic"],
  "Museum": ["curated", "reverent"],
  "Hospital": ["sterile", "beeping"],
  "Doctor's Office": ["clinical", "waitlisted"],
  "Dentist": ["drilled", "numbing"],
  "Pharmacy": ["prescribed", "counted"],
  "Bank": ["vaulted", "secured"],
  "Post Office": ["stamped", "queued"],
  "Police Station": ["badged", "procedural"],
  "Fire Station": ["sirened", "heroic"],
  "Church": ["hymnal", "congregational"],
  "Airport": ["delayed", "boarding"],
  "Train Station": ["platformed", "commutable"],
  "Bus Stop": ["sheltered", "scheduled"],
  "Gas Station": ["pumped", "convenient"],
  "Parking Lot": ["asphalt", "circling"],
  "Hotel": ["transient", "checkinable"],
  "Campground": ["tentable", "smoky"],
  "Farm": ["pastoral", "harvestable"],
  "Barn": ["rustic", "agrarian"],
  "Forest": ["wooded", "shaded"],
  "Mountains": ["elevated", "alpine"],
  "Lake": ["reflective", "rippled"],
  "River": ["flowing", "meandering"],
  "Ocean": ["salty", "boundless"],
  "Island": ["isolated", "shorelined"],
  "Desert": ["arid", "sunscorched"],
  "Cave": ["echoing", "subterranean"],
  "Waterfall": ["misty", "cascading"],
  "Stadium": ["roaring", "tiered"],
  "Soccer Field": ["grassy", "netted"],
  "Basketball Court": ["hardwood", "squeaky"],
  "Skate Park": ["ramped", "scraped"],
  "Bowling Alley": ["guttered", "spared"],
  "Arcade": ["coinfed", "flashing"],
  "Amusement Park": ["queued", "thrilling"],
  "Roller Coaster": ["vertiginous", "strapped"],
  "Water Park": ["splashed", "slippery"],
  "Disneyland": ["branded", "enchanted"],
  "Grandma's House": ["nostalgic", "indulgent"],
  "Friend's House": ["borrowed", "overnight"],
  "Daycare": ["supervised", "napping"],
  "College": ["tuitioned", "sprawling"],
  "Dorm": ["bunked", "communal"],
  "Locker Room": ["sweaty", "communal"],
  "Nurse's Office": ["bandaged", "feverish"],
  "Principal's Office": ["disciplinary", "intimidating"],
  "Barbershop": ["clipped", "conversational"],
  "Hair Salon": ["coiffed", "mirrored"],
  "Laundromat": ["spinning", "coinfed"],
  "Pet Store": ["caged", "yipping"],
  "Toy Store": ["colorful", "packaged"],
  "Bookstore": ["browsable", "papery"],
  "Hardware Store": ["bolted", "aisled"],
  "Costco": ["bulked", "membership"],
  "Walmart": ["fluorescent", "vast"],
  "Target": ["suburban", "affordable"],
  "McDonald's": ["expedited", "driveable"],
  "Starbucks": ["overpriced", "customized"],
  "Subway": ["underground", "turnstiled"],
  "Downtown": ["urban", "gentrified"],
  "Neighborhood": ["familiar", "walkable"],
  "Sidewalk": ["paved", "pedestrian"],
  "Street": ["trafficked", "asphalted"],
  "Bridge": ["spanning", "elevated"],
  "Tunnel": ["enclosed", "echoing"],
  "Highway": ["congested", "commutable"],
};
