/** @type {Record<string, string[]>} */
export default {
  "Soccer": ["rivalrous"],
  "Football": ["televised"],
  "Basketball": ["collegiate"],
  "Baseball": ["nostalgic"],
  "Softball": ["recreational"],
  "Tennis": ["rivalrous"],
  "Golf": ["leisurely"],
  "Volleyball": ["recreational"],
  "Hockey": ["aggressive"],
  "Lacrosse": ["regional"],
  "Rugby": ["combative"],
  "Cricket": ["international"],
  "Bowling": ["recreational"],
  "Swimming": ["aquatic"],
  "Diving": ["aquatic"],
  "Track": ["timed"],
  "Running": ["endurance"],
  "Marathon": ["grueling"],
  "Sprinting": ["explosive"],
  "Hurdles": ["technical"],
  "Long Jump": ["technical"],
  "High Jump": ["technical"],
  "Gymnastics": ["precise"],
  "Wrestling": ["combative"],
  "Boxing": ["combative"],
  "Karate": ["martial"],
  "Fencing": ["martial"],
  "Archery": ["precise"],
  "Skateboarding": ["rebellious"],
  "Snowboarding": ["alpine"],
  "Skiing": ["alpine"],
  "Ice Skating": ["performative"],
  "Surfing": ["aquatic"],
  "Fishing": ["patient"],
  "Hunting": ["controversial"],
  "Horseback Riding": ["equestrian"],
  "Cycling": ["endurance"],
  "Biking": ["recreational"],
  "Roller Skating": ["nostalgic"],
  "Rollerblading": ["nostalgic"],
  "Scooter": ["childhood"],
  "Skateboard": ["rebellious"],
  "Trampoline": ["playground"],
  "Jump Rope": ["rhythmic"],
  "Hopscotch": ["childhood"],
  "Tag": ["childhood"],
  "Hide and Seek": ["childhood"],
  "Capture the Flag": ["childhood"],
  "Dodgeball": ["aggressive"],
  "Kickball": ["childhood"],
  "Frisbee": ["casual"],
  "Badminton": ["casual"],
  "Ping Pong": ["casual"],
  "Pool": ["casual"],
  "Billiards": ["casual"],
  "Darts": ["pub"],
  "Chess": ["strategic"],
  "Checkers": ["nostalgic"],
  "Video Games": ["sedentary"],
  "Yoga": ["mindful"],
  "Dance": ["performative"],
  "Cheerleading": ["spectacle"],
  "Marching Band": ["ceremonial"],
  "Gym Class": ["mandatory"],
  "PE": ["mandatory"],
  "Team": ["cooperative"],
  "Coach": ["authoritative"],
  "Referee": ["officiated"],
  "Umpire": ["officiated"],
  "Score": ["measurable"],
  "Goal": ["decisive"],
  "Touchdown": ["decisive"],
  "Home Run": ["dramatic"],
  "Slam Dunk": ["dramatic"],
  "Hat Trick": ["rare"],
  "Penalty Kick": ["pressured"],
  "Free Throw": ["pressured"],
  "Strike": ["decisive"],
  "Spare": ["redemptive"],
  "Medal": ["ceremonial"],
  "Trophy": ["ceremonial"],
  "Winner": ["celebratory"],
  "Loser": ["subdued"],
  "Tie Game": ["anticlimactic"],
  "Overtime": ["dramatic"],
  "Playoffs": ["elimination"],
  "Championship": ["prestigious"],
  "Super Bowl": ["spectacle"],
  "World Cup": ["patriotic"],
  "Olympics": ["prestigious"],
  "ESPN": ["televised"],
  "Sports Center": ["recap"],
  "Fantasy Football": ["statistical"],
  "Pickup Game": ["casual"],
  "Tryouts": ["selective"],
  "Practice": ["repetitive"],
  "Warm-Up": ["preparatory"],
  "Cool Down": ["recovery"],
  "Injury": ["setback"],
  "Ice Pack": ["recovery"],
  "Water Break": ["intermittent"],
  "Rock Climbing": ["technical"],
};
