export type WordCategory = {
  id: string;
  name: string;
  words: string[];
};

export const WORD_CATEGORIES: WordCategory[] = [
  {
    id: "food",
    name: "Food & Drinks",
    words: [
      "Pizza",
      "Sushi",
      "Tacos",
      "Burger",
      "Pasta",
      "Ramen",
      "Ice Cream",
      "Coffee",
      "Smoothie",
      "Pancakes",
      "Steak",
      "Salad",
      "Donuts",
      "Hot Dog",
      "Nachos",
    ],
  },
  {
    id: "animals",
    name: "Animals",
    words: [
      "Dolphin",
      "Penguin",
      "Elephant",
      "Tiger",
      "Owl",
      "Kangaroo",
      "Panda",
      "Octopus",
      "Giraffe",
      "Wolf",
      "Parrot",
      "Shark",
      "Butterfly",
      "Fox",
      "Turtle",
    ],
  },
  {
    id: "places",
    name: "Places",
    words: [
      "Beach",
      "Library",
      "Hospital",
      "Airport",
      "Museum",
      "Stadium",
      "School",
      "Zoo",
      "Mall",
      "Park",
      "Castle",
      "Farm",
      "Theater",
      "Hotel",
      "Subway",
    ],
  },
  {
    id: "movies",
    name: "Movies & TV",
    words: [
      "Superhero",
      "Horror",
      "Comedy",
      "Documentary",
      "Cartoon",
      "Reality Show",
      "Sitcom",
      "Thriller",
      "Romance",
      "Sci-Fi",
      "Western",
      "Musical",
      "Game Show",
      "Talk Show",
      "News",
    ],
  },
  {
    id: "sports",
    name: "Sports",
    words: [
      "Soccer",
      "Basketball",
      "Tennis",
      "Swimming",
      "Golf",
      "Boxing",
      "Skateboarding",
      "Volleyball",
      "Baseball",
      "Hockey",
      "Cycling",
      "Skiing",
      "Surfing",
      "Wrestling",
      "Gymnastics",
    ],
  },
  {
    id: "jobs",
    name: "Jobs",
    words: [
      "Doctor",
      "Teacher",
      "Chef",
      "Pilot",
      "Artist",
      "Engineer",
      "Firefighter",
      "Lawyer",
      "Musician",
      "Scientist",
      "Athlete",
      "Detective",
      "Farmer",
      "Architect",
      "Veterinarian",
    ],
  },
  {
    id: "objects",
    name: "Everyday Objects",
    words: [
      "Umbrella",
      "Backpack",
      "Headphones",
      "Watch",
      "Sunglasses",
      "Keyboard",
      "Lamp",
      "Mirror",
      "Wallet",
      "Toothbrush",
      "Pillow",
      "Scissors",
      "Notebook",
      "Water Bottle",
      "Flashlight",
    ],
  },
  {
    id: "nature",
    name: "Nature",
    words: [
      "Rainbow",
      "Volcano",
      "Waterfall",
      "Desert",
      "Forest",
      "Thunderstorm",
      "Aurora",
      "Canyon",
      "Glacier",
      "Coral Reef",
      "Tornado",
      "Meadow",
      "Cave",
      "Island",
      "River",
    ],
  },
];
