export type WordCategory = {
  id: string;
  name: string;
  words: string[];
};

export const WORD_CATEGORIES: WordCategory[] = [
  {
    id: "food",
    name: "Food & Drinks",
    words: [
      "Pizza",
      "Sushi",
      "Tacos",
      "Burger",
      "Pasta",
      "Ramen",
      "Ice Cream",
      "Coffee",
      "Smoothie",
      "Pancakes",
      "Steak",
      "Salad",
      "Donuts",
      "Hot Dog",
      "Nachos",
      "Burrito",
      "Lasagna",
      "Waffles",
      "French Fries",
      "Grilled Cheese",
      "Mac and Cheese",
      "Chicken Wings",
      "Fish and Chips",
      "Pad Thai",
      "Pho",
      "Curry",
      "Dumplings",
      "Spring Rolls",
      "Guacamole",
      "Hummus",
      "Bagel",
      "Croissant",
      "Muffin",
      "Cupcake",
      "Brownie",
      "Cheesecake",
      "Apple Pie",
      "Chocolate",
      "Popcorn",
      "Pretzel",
      "Chips",
      "Salsa",
      "Omelette",
      "Bacon",
      "Sausage",
      "Meatballs",
      "Spaghetti",
      "Ravioli",
      "Quesadilla",
      "Enchilada",
      "Falafel",
      "Shawarma",
      "Kebab",
      "Paella",
      "Risotto",
      "Clam Chowder",
      "Tomato Soup",
      "Caesar Salad",
      "Coleslaw",
      "Mashed Potatoes",
      "Corn on the Cob",
      "Avocado Toast",
      "Cereal",
      "Oatmeal",
      "Yogurt",
      "Granola",
      "Milkshake",
      "Lemonade",
      "Iced Tea",
      "Hot Chocolate",
      "Bubble Tea",
      "Espresso",
      "Cappuccino",
      "Latte",
      "Green Tea",
      "Orange Juice",
      "Apple Juice",
      "Soda",
      "Energy Drink",
      "Coconut Water",
      "Sparkling Water",
      "Wine",
      "Champagne",
      "Cocktail",
      "Margarita",
      "Mojito",
      "Sangria",
      "Pickles",
      "Olives",
      "Cheese",
      "Butter",
      "Honey",
      "Jam",
      "Peanut Butter",
      "Maple Syrup",
      "Ketchup",
      "Mustard",
      "Mayonnaise",
      "Hot Sauce",
      "Ranch",
      "BBQ Sauce",
    ],
  },
  {
    id: "animals",
    name: "Animals",
    words: [
      "Dolphin",
      "Penguin",
      "Elephant",
      "Tiger",
      "Owl",
      "Kangaroo",
      "Panda",
      "Octopus",
      "Giraffe",
      "Wolf",
      "Parrot",
      "Shark",
      "Butterfly",
      "Fox",
      "Turtle",
      "Lion",
      "Bear",
      "Gorilla",
      "Chimpanzee",
      "Monkey",
      "Zebra",
      "Hippo",
      "Rhino",
      "Cheetah",
      "Leopard",
      "Jaguar",
      "Cougar",
      "Lynx",
      "Bobcat",
      "Raccoon",
      "Skunk",
      "Deer",
      "Moose",
      "Elk",
      "Bison",
      "Buffalo",
      "Horse",
      "Donkey",
      "Camel",
      "Llama",
      "Alpaca",
      "Sheep",
      "Goat",
      "Pig",
      "Cow",
      "Chicken",
      "Rooster",
      "Duck",
      "Goose",
      "Turkey",
      "Eagle",
      "Hawk",
      "Falcon",
      "Crow",
      "Raven",
      "Sparrow",
      "Robin",
      "Hummingbird",
      "Flamingo",
      "Pelican",
      "Seagull",
      "Pigeon",
      "Bat",
      "Squirrel",
      "Chipmunk",
      "Beaver",
      "Otter",
      "Seal",
      "Walrus",
      "Whale",
      "Orca",
      "Jellyfish",
      "Starfish",
      "Crab",
      "Lobster",
      "Shrimp",
      "Squid",
      "Seahorse",
      "Clownfish",
      "Stingray",
      "Eel",
      "Salmon",
      "Goldfish",
      "Koi",
      "Frog",
      "Toad",
      "Salamander",
      "Snake",
      "Lizard",
      "Gecko",
      "Iguana",
      "Chameleon",
      "Crocodile",
      "Alligator",
      "Tortoise",
      "Snail",
      "Slug",
      "Spider",
      "Scorpion",
      "Ant",
      "Bee",
      "Wasp",
      "Ladybug",
      "Dragonfly",
      "Mosquito",
      "Grasshopper",
      "Cricket",
      "Beetle",
      "Caterpillar",
      "Moth",
      "Hamster",
      "Guinea Pig",
      "Rabbit",
      "Ferret",
      "Chinchilla",
      "Hedgehog",
      "Cat",
      "Dog",
      "Golden Retriever",
      "Poodle",
      "Bulldog",
      "Husky",
      "Corgi",
    ],
  },
  {
    id: "places",
    name: "Places",
    words: [
      "Beach",
      "Library",
      "Hospital",
      "Airport",
      "Museum",
      "Stadium",
      "School",
      "Zoo",
      "Mall",
      "Park",
      "Castle",
      "Farm",
      "Theater",
      "Hotel",
      "Subway",
      "Restaurant",
      "Cafe",
      "Bakery",
      "Grocery Store",
      "Pharmacy",
      "Bank",
      "Post Office",
      "Police Station",
      "Fire Station",
      "Courthouse",
      "Church",
      "Temple",
      "Mosque",
      "Synagogue",
      "Cemetery",
      "Playground",
      "Skate Park",
      "Gym",
      "Pool",
      "Spa",
      "Salon",
      "Barbershop",
      "Laundromat",
      "Gas Station",
      "Parking Garage",
      "Bus Stop",
      "Train Station",
      "Harbor",
      "Marina",
      "Lighthouse",
      "Bridge",
      "Tunnel",
      "Highway",
      "Intersection",
      "Crosswalk",
      "Sidewalk",
      "Alley",
      "Downtown",
      "Suburb",
      "Neighborhood",
      "Apartment",
      "House",
      "Mansion",
      "Cottage",
      "Cabin",
      "Treehouse",
      "Basement",
      "Attic",
      "Garage",
      "Backyard",
      "Garden",
      "Greenhouse",
      "Orchard",
      "Vineyard",
      "Barn",
      "Stable",
      "Aquarium",
      "Planetarium",
      "Observatory",
      "Laboratory",
      "Factory",
      "Warehouse",
      "Office",
      "Cubicle",
      "Conference Room",
      "Classroom",
      "Lecture Hall",
      "Dormitory",
      "Cafeteria",
      "Locker Room",
      "Nurse's Office",
      "Principal's Office",
      "Amusement Park",
      "Roller Coaster",
      "Ferris Wheel",
      "Water Park",
      "Arcade",
      "Bowling Alley",
      "Mini Golf",
      "Campground",
      "Hiking Trail",
      "Mountain",
      "Valley",
      "Cliff",
      "Cave",
      "Waterfall",
      "Lake",
      "Pond",
      "River",
      "Stream",
      "Ocean",
      "Island",
      "Peninsula",
      "Desert",
      "Oasis",
      "Jungle",
      "Rainforest",
      "Swamp",
      "Marsh",
      "Prairie",
      "Tundra",
      "Arctic",
      "Volcano",
      "Geyser",
      "Hot Spring",
      "Ski Resort",
      "Beach Resort",
      "Cruise Ship",
      "Airplane",
      "Space Station",
    ],
  },
  {
    id: "movies",
    name: "Movies & TV",
    words: [
      "Superhero",
      "Horror",
      "Comedy",
      "Documentary",
      "Cartoon",
      "Reality Show",
      "Sitcom",
      "Thriller",
      "Romance",
      "Sci-Fi",
      "Western",
      "Musical",
      "Game Show",
      "Talk Show",
      "News",
      "Action",
      "Adventure",
      "Fantasy",
      "Mystery",
      "Crime",
      "Noir",
      "Heist",
      "Spy",
      "War",
      "Historical",
      "Biopic",
      "Sports Movie",
      "Coming of Age",
      "Teen Drama",
      "Soap Opera",
      "Variety Show",
      "Cooking Show",
      "Travel Show",
      "Nature Documentary",
      "True Crime",
      "Stand-Up",
      "Sketch Comedy",
      "Animated Series",
      "Anime",
      "Stop Motion",
      "Puppet Show",
      "Talent Show",
      "Quiz Show",
      "Survival Show",
      "Dating Show",
      "Home Renovation",
      "Makeover Show",
      "Courtroom Drama",
      "Medical Drama",
      "Police Procedural",
      "Space Opera",
      "Time Travel",
      "Zombie",
      "Vampire",
      "Werewolf",
      "Alien",
      "Robot",
      "Dragon",
      "Wizard",
      "Pirate",
      "Ninja",
      "Samurai",
      "Knight",
      "Princess",
      "Prince",
      "Villain",
      "Sidekick",
      "Plot Twist",
      "Cliffhanger",
      "Flashback",
      "Sequel",
      "Prequel",
      "Remake",
      "Franchise",
      "Box Office",
      "Oscars",
      "Red Carpet",
      "Movie Theater",
      "Drive-In",
      "Streaming",
      "Binge Watch",
      "Season Finale",
      "Pilot Episode",
      "Credits",
      "Trailer",
      "Soundtrack",
      "Special Effects",
      "Stunt",
      "Chase Scene",
      "Fight Scene",
      "Love Triangle",
      "Happy Ending",
      "Twist Ending",
      "Jump Scare",
      "Plot Hole",
      "Fan Theory",
      "Spoiler",
      "Director",
      "Producer",
      "Screenwriter",
      "Cinematography",
      "Costume Design",
      "Makeup Effects",
      "Green Screen",
      "Subtitles",
      "Dubbing",
      "Commercial Break",
      "Theme Song",
      "Catchphrase",
    ],
  },
  {
    id: "sports",
    name: "Sports",
    words: [
      "Soccer",
      "Basketball",
      "Tennis",
      "Swimming",
      "Golf",
      "Boxing",
      "Skateboarding",
      "Volleyball",
      "Baseball",
      "Hockey",
      "Cycling",
      "Skiing",
      "Surfing",
      "Wrestling",
      "Gymnastics",
      "Football",
      "Rugby",
      "Cricket",
      "Badminton",
      "Table Tennis",
      "Squash",
      "Racquetball",
      "Lacrosse",
      "Field Hockey",
      "Water Polo",
      "Diving",
      "Synchronized Swimming",
      "Track and Field",
      "Marathon",
      "Sprint",
      "Hurdles",
      "Long Jump",
      "High Jump",
      "Pole Vault",
      "Shot Put",
      "Discus",
      "Javelin",
      "Triathlon",
      "Decathlon",
      "Weightlifting",
      "Powerlifting",
      "CrossFit",
      "Bodybuilding",
      "MMA",
      "Karate",
      "Judo",
      "Taekwondo",
      "Fencing",
      "Archery",
      "Shooting",
      "Biathlon",
      "Snowboarding",
      "Figure Skating",
      "Speed Skating",
      "Curling",
      "Bobsled",
      "Luge",
      "Skeleton",
      "Rock Climbing",
      "Bouldering",
      "Mountaineering",
      "Hiking",
      "Trail Running",
      "Obstacle Course",
      "Parkour",
      "BMX",
      "Motocross",
      "Formula One",
      "NASCAR",
      "Drag Racing",
      "Horse Racing",
      "Polo",
      "Rodeo",
      "Bull Riding",
      "Rowing",
      "Kayaking",
      "Canoeing",
      "Sailing",
      "Windsurfing",
      "Kitesurfing",
      "Wakeboarding",
      "Water Skiing",
      "Snorkeling",
      "Scuba Diving",
      "Fishing",
      "Bowling",
      "Darts",
      "Billiards",
      "Snooker",
      "Chess",
      "Esports",
      "Pickleball",
      "Handball",
      "Dodgeball",
      "Kickball",
      "Softball",
      "Ultimate Frisbee",
      "Disc Golf",
      "Cornhole",
      "Hopscotch",
      "Jump Rope",
      "Yoga",
      "Pilates",
      "Aerobics",
      "Zumba",
      "Dance Sport",
      "Cheerleading",
      "Marching Band",
      "Halfpipe",
      "Penalty Kick",
      "Home Run",
      "Touchdown",
      "Slam Dunk",
      "Hat Trick",
      "Knockout",
      "Checkmate",
      "Olympics",
      "World Cup",
      "Super Bowl",
      "Wimbledon",
      "March Madness",
      "Medal",
      "Trophy",
      "Championship",
      "Playoffs",
      "Overtime",
      "Referee",
      "Coach",
      "Teammate",
      "Rivalry",
      "Underdog",
      "Comeback",
      "Injury Timeout",
    ],
  },
  {
    id: "jobs",
    name: "Jobs",
    words: [
      "Doctor",
      "Teacher",
      "Chef",
      "Pilot",
      "Artist",
      "Engineer",
      "Firefighter",
      "Lawyer",
      "Musician",
      "Scientist",
      "Athlete",
      "Detective",
      "Farmer",
      "Architect",
      "Veterinarian",
      "Nurse",
      "Surgeon",
      "Dentist",
      "Pharmacist",
      "Therapist",
      "Psychologist",
      "Paramedic",
      "Midwife",
      "Optometrist",
      "Chiropractor",
      "Professor",
      "Principal",
      "Tutor",
      "Librarian",
      "Coach",
      "Babysitter",
      "Social Worker",
      "Counselor",
      "Police Officer",
      "Sheriff",
      "FBI Agent",
      "Judge",
      "Paralegal",
      "Accountant",
      "Banker",
      "Financial Advisor",
      "Stockbroker",
      "Real Estate Agent",
      "Insurance Agent",
      "Salesperson",
      "Cashier",
      "Manager",
      "CEO",
      "Entrepreneur",
      "Investor",
      "Consultant",
      "Recruiter",
      "HR Specialist",
      "Marketing Manager",
      "Graphic Designer",
      "Web Developer",
      "Software Engineer",
      "Data Scientist",
      "IT Support",
      "Electrician",
      "Plumber",
      "Carpenter",
      "Mechanic",
      "Welder",
      "Construction Worker",
      "Roofer",
      "Painter",
      "Landscaper",
      "Janitor",
      "Housekeeper",
      "Barista",
      "Bartender",
      "Waiter",
      "Host",
      "Baker",
      "Butcher",
      "Florist",
      "Tailor",
      "Fashion Designer",
      "Model",
      "Actor",
      "Director",
      "Producer",
      "Camera Operator",
      "Journalist",
      "Reporter",
      "Editor",
      "Photographer",
      "Videographer",
      "Influencer",
      "Streamer",
      "Author",
      "Poet",
      "Illustrator",
      "Animator",
      "Game Developer",
      "UX Designer",
      "Interior Designer",
      "Urban Planner",
      "Civil Engineer",
      "Aerospace Engineer",
      "Biologist",
      "Chemist",
      "Physicist",
      "Astronomer",
      "Geologist",
      "Archaeologist",
      "Historian",
      "Curator",
      "Tour Guide",
      "Flight Attendant",
      "Air Traffic Controller",
      "Truck Driver",
      "Delivery Driver",
      "Mail Carrier",
      "Bus Driver",
      "Taxi Driver",
      "Uber Driver",
      "Sailor",
      "Fisherman",
      "Miner",
      "Oil Rig Worker",
      "Soldier",
      "Marine",
      "Astronaut",
      "Lifeguard",
      "Park Ranger",
      "Zookeeper",
      "Dog Walker",
      "Personal Trainer",
      "Nutritionist",
      "Yoga Instructor",
      "Hair Stylist",
      "Makeup Artist",
      "Tattoo Artist",
      "DJ",
      "Event Planner",
      "Wedding Planner",
      "Magician",
      "Clown",
      "Security Guard",
      "Bouncer",
      "Private Investigator",
    ],
  },
  {
    id: "objects",
    name: "Everyday Objects",
    words: [
      "Umbrella",
      "Backpack",
      "Headphones",
      "Watch",
      "Sunglasses",
      "Keyboard",
      "Lamp",
      "Mirror",
      "Wallet",
      "Toothbrush",
      "Pillow",
      "Scissors",
      "Notebook",
      "Water Bottle",
      "Flashlight",
      "Phone",
      "Laptop",
      "Tablet",
      "Charger",
      "Power Bank",
      "Mouse",
      "Monitor",
      "Webcam",
      "Microphone",
      "Speaker",
      "Remote Control",
      "Television",
      "Game Controller",
      "Console",
      "VR Headset",
      "Camera",
      "Tripod",
      "SD Card",
      "USB Drive",
      "Hard Drive",
      "Router",
      "Modem",
      "Ethernet Cable",
      "Extension Cord",
      "Outlet",
      "Light Bulb",
      "Candle",
      "Lighter",
      "Matches",
      "Fan",
      "Heater",
      "Air Conditioner",
      "Thermostat",
      "Smoke Detector",
      "Fire Extinguisher",
      "Doorbell",
      "Key",
      "Lock",
      "Doorknob",
      "Hammer",
      "Screwdriver",
      "Wrench",
      "Pliers",
      "Tape Measure",
      "Duct Tape",
      "Glue",
      "Stapler",
      "Paper Clip",
      "Rubber Band",
      "Push Pin",
      "Whiteboard",
      "Marker",
      "Pen",
      "Pencil",
      "Eraser",
      "Ruler",
      "Calculator",
      "Calendar",
      "Clock",
      "Alarm Clock",
      "Stopwatch",
      "Thermometer",
      "Scale",
      "Trash Can",
      "Recycling Bin",
      "Vacuum",
      "Broom",
      "Mop",
      "Sponge",
      "Dish Soap",
      "Laundry Basket",
      "Iron",
      "Hanger",
      "Clothes Pin",
      "Sewing Kit",
      "Button",
      "Zipper",
      "Shoelace",
      "Belt",
      "Hat",
      "Gloves",
      "Scarf",
      "Coat",
      "Jacket",
      "Sneakers",
      "Boots",
      "Sandals",
      "Slippers",
      "Towel",
      "Washcloth",
      "Soap",
      "Shampoo",
      "Conditioner",
      "Lotion",
      "Razor",
      "Hairbrush",
      "Comb",
      "Hair Dryer",
      "Curling Iron",
      "Straightener",
      "Nail Clipper",
      "Tweezers",
      "Bandage",
      "First Aid Kit",
      "Medicine",
      "Vitamins",
      "Glasses",
      "Contact Case",
      "Mug",
      "Cup",
      "Plate",
      "Bowl",
      "Fork",
      "Knife",
      "Spoon",
      "Chopsticks",
      "Pot",
      "Pan",
      "Cutting Board",
      "Oven Mitt",
      "Blender",
      "Toaster",
      "Microwave",
      "Refrigerator",
      "Freezer",
      "Coffee Maker",
      "Kettle",
      "Grater",
      "Can Opener",
      "Corkscrew",
      "Cooler",
      "Lunch Box",
      "Tupperware",
      "Aluminum Foil",
      "Plastic Wrap",
      "Ziploc Bag",
      "Book",
      "Bookmark",
      "Magazine",
      "Newspaper",
      "Envelope",
      "Stamp",
      "Package",
      "Gift Wrap",
      "Balloon",
      "Party Hat",
      "Confetti",
      "Board Game",
      "Playing Cards",
      "Dice",
      "Puzzle",
      "Teddy Bear",
      "Action Figure",
      "Yo-Yo",
      "Frisbee",
      "Ball",
      "Bicycle",
      "Helmet",
      "Skateboard",
      "Roller Skates",
      "Tent",
      "Sleeping Bag",
      "Compass",
      "Map",
      "Binoculars",
      "Telescope",
      "Magnifying Glass",
      "Toolbox",
      "Safe",
      "Piggy Bank",
      "Credit Card",
      "Receipt",
      "Shopping Cart",
      "Basket",
      "Suitcase",
      "Passport",
      "Boarding Pass",
      "Ticket",
      "License",
    ],
  },
  {
    id: "nature",
    name: "Nature",
    words: [
      "Rainbow",
      "Volcano",
      "Waterfall",
      "Desert",
      "Forest",
      "Thunderstorm",
      "Aurora",
      "Canyon",
      "Glacier",
      "Coral Reef",
      "Tornado",
      "Meadow",
      "Cave",
      "Island",
      "River",
      "Ocean",
      "Sea",
      "Wave",
      "Tide",
      "Tsunami",
      "Hurricane",
      "Typhoon",
      "Cyclone",
      "Blizzard",
      "Snowstorm",
      "Hail",
      "Sleet",
      "Frost",
      "Icicle",
      "Avalanche",
      "Earthquake",
      "Landslide",
      "Flood",
      "Drought",
      "Wildfire",
      "Lightning",
      "Thunder",
      "Cloud",
      "Fog",
      "Mist",
      "Dew",
      "Rain",
      "Snow",
      "Sunshine",
      "Sunset",
      "Sunrise",
      "Eclipse",
      "Full Moon",
      "Crescent Moon",
      "Star",
      "Constellation",
      "Milky Way",
      "Comet",
      "Meteor",
      "Asteroid",
      "Planet",
      "Solar System",
      "Galaxy",
      "Nebula",
      "Black Hole",
      "Mountain Peak",
      "Hill",
      "Plateau",
      "Basin",
      "Fjord",
      "Delta",
      "Estuary",
      "Lagoon",
      "Bay",
      "Gulf",
      "Strait",
      "Reef",
      "Atoll",
      "Archipelago",
      "Coastline",
      "Sand Dune",
      "Oasis",
      "Savanna",
      "Grassland",
      "Wetland",
      "Bog",
      "Fen",
      "Mangrove",
      "Redwood",
      "Oak Tree",
      "Pine Tree",
      "Palm Tree",
      "Willow",
      "Birch",
      "Maple",
      "Cherry Blossom",
      "Cactus",
      "Fern",
      "Moss",
      "Lichen",
      "Mushroom",
      "Wildflower",
      "Sunflower",
      "Rose",
      "Tulip",
      "Daisy",
      "Lily",
      "Orchid",
      "Lavender",
      "Dandelion",
      "Vine",
      "Ivy",
      "Bamboo",
      "Seaweed",
      "Kelp",
      "Plankton",
      "Coral",
      "Shell",
      "Fossil",
      "Amber",
      "Crystal",
      "Quartz",
      "Granite",
      "Marble",
      "Sandstone",
      "Limestone",
      "Obsidian",
      "Geode",
      "Hot Spring",
      "Geyser",
      "Mineral Spring",
      "Underground River",
      "Stalactite",
      "Stalagmite",
      "Sinkhole",
      "Grotto",
      "Cliffside",
      "Rapids",
      "Whirlpool",
      "Spring",
      "Brook",
      "Creek",
      "Waterfall Pool",
      "Evergreen",
      "Deciduous",
      "Canopy",
      "Underbrush",
      "Tree Ring",
      "Acorn",
      "Pinecone",
      "Pollen",
      "Honeycomb",
      "Nest",
      "Burrow",
      "Den",
      "Hibernation",
      "Migration",
      "Ecosystem",
      "Habitat",
      "Biodiversity",
      "Conservation",
      "National Park",
      "Nature Reserve",
      "Wilderness",
    ],
  },
];
